### ISSUE TITLE
If ssh login tracking script fails, it blocks ssh logins

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern_aws#173]
Instead, it should still allow the ssh login, otherwise we can't manage our machines.

```
Traceback (most recent call last):
  File "/usr/bin/sshalert.py", line 17, in <module>
    whitelisted = redis_shell is not None and redis_shell.exists('sshalert-whitelist:%s' % ip)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 855, in exists
    return self.execute_command('EXISTS', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 8 connecting to redis.getlantern.org:6380. _ssl.c:510: EOF occurred in violation of protocol.
Connection to xxx.xxx.xxx.xx closed.
```

**Comment by aranhoide** [comment]
Hotfixed via https://github.com/getlantern/lantern_aws/commit/e5eac285a4b1486fe2e3a16b8fb4028ae86710de .  It's not the optimal fix, but it's a foolproof one that could be deployed quickly.
