### ISSUE TITLE
Exception trying to offload server

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern_aws#196]
Caught this in Vultr Tokyo's syslog:

```
May 28 16:57:00 cm-vltok1 offload: Starting offload server for region sea.
May 28 16:57:00 cm-vltok1 offload: Offloading users from fp-https-vltok1-20160420-058 (45.32.28.217)
May 28 16:57:00 cm-vltok1 offload: Traceback (most recent call last):
May 28 16:57:00 cm-vltok1 offload:   File "/usr/bin/offload.py", line 36, in <module>
May 28 16:57:00 cm-vltok1 offload:     run()
May 28 16:57:00 cm-vltok1 offload:   File "/usr/bin/offload.py", line 26, in run
May 28 16:57:00 cm-vltok1 offload:     vps_util.actually_offload_proxy(name, ip, pipeline=txn)
May 28 16:57:00 cm-vltok1 offload:   File "/usr/local/lib/pylib/vps_util.py", line 158, in actually_offload_proxy
May 28 16:57:00 cm-vltok1 offload:     packed_srv = redis_util.pack_srv(srv)
May 28 16:57:00 cm-vltok1 offload:   File "/usr/local/lib/pylib/redis_util.py", line 126, in pack_srv
May 28 16:57:00 cm-vltok1 offload:     srv = int(srv)
May 28 16:57:00 cm-vltok1 offload: TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by aranhoide** [comment]
Sure enough, the involved proxy doesn't exist.  Manual ops (e.g. someone retiring this server) could have done this.  I'll check for this case here.
