### ISSUE TITLE
offload_users.py not working for some IPs

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern_aws#236]
Some IPs are getting the following trace while others work:

This is for `fp-doams3-20160331-006`

```
>>> sl.offload_users(ip='188.166.31.147')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "secret_lib.py", line 578, in offload_users
    region = vps_util.region_by_name(name)
  File "/Users/afisk/lantern_aws/lib/vps_util.py", line 280, in region_by_name
    return region_by_dc(dc_by_name(name))
  File "/Users/afisk/lantern_aws/lib/vps_util.py", line 310, in dc_by_name
    return dc_by_cm(cm_by_name(name))
  File "/Users/afisk/lantern_aws/lib/vps_util.py", line 273, in cm_by_name
    if name.startswith('fp-nl-'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by myleshorton** [comment]
FYI @aranhoide in case this is a simple fix. Just in the backlog for now.

**Comment by fffw** [comment]
`188.166.31.147` is not a Lantern proxy server anymore, that makes `name` to be `None`.

**Comment by myleshorton** [comment]
That'll do it @fffw! It was alarming today, but I guess maybe it was automatically closed? Same with fp-doams3-20160128-043 (188.166.2.133)

**Comment by aranhoide** [comment]
This will be much easier to diagnose when https://github.com/getlantern/lantern_aws/issues/182 is completed and deployed.

**Comment by myleshorton** [comment]
OK makes sense @aranhoide. One curious aspect is that I didn't see any indication in the ops-alerts that these servers were closing due to load or anything like that. I'll close this for now.
